# Uncomment the next line to define a global platform for your project
#基于AsyncDisplayKit布局与WCDB缓存写的一个动态demo（仿照朋友圈）

platform :ios, '8.0'
target 'AsyncDisplayForDynamic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AsyncDisplayForDynamic
# pod 'AFNetworking', '~> 3.1.0'
# pod 'SDWebImage', '~> 4.0.0'
# pod 'FLAnimatedImage', '~> 1.0.12'
# pod 'MJRefresh', '~> 3.1.15'
# pod 'MJExtension', '~> 3.0.13'
# pod 'JSONModel', '~> 1.7.0'
# pod 'YYText', '~> 1.0.7'
# pod 'MBProgressHUD', '~> 1.1.0'
 
 pod 'AsyncDisplayKit', '~> 2.2.1'
 pod 'WCDB', '~> 1.0.6'


end
